Metrics/LineLength:
  # We set up error messages here and I don't want people suboptimising by making
  # their variables shorter... so we'll relax this a bit. Usually lines lime this:
  # ```
  #    AIRPORT_REFUSED_MESSAGE = "Airport has refused our landing! Probably bad weather"
  # ```
  # Would get extracted to locales, but that's out of the fence here so.
  Max: 100

  # While test refactoring is good, I suspect it's out of scope for week 1
  Exclude:
    - 'spec/**/*'

Metrics/BlockLength:
  # While test refactoring is good, I suspect it's out of scope for week 1
  Exclude:
    - 'spec/**/*'

# I've been quite careful about which style cops I've enabled
# Why? My feeling is that style cops can create lots of linter noise that
# is hard for a beginner to handle. This focuses the linting onto:
#   * Indentation & whitespace (inconsistency, really gross stuff like `a=1`)
#   * Easy wins in expressiveness (e.g. gurad clauses — nice opportunity to inject concretes)
#   * Egregious non-idiomatic ruby like `def getFilename`
#
# Quote cops are notable by their absence. They add a lot of noise and they're
# annoying to fix so a good opportunity to turn devs off of the utility of
# linting. Hopefully they pick them up later :)

Layout/IndentationConsistency:
  Enabled: true
Layout/IndentationWidth:
  Enabled: true
Layout/AccessorMethodName:
  Enabled: true
Layout/BlockEndNewline:
  Enabled: true
Layout/ClassAndModuleCamelCase:
  Enabled: true
Layout/ConstantName:
  Enabled: true
Layout/DefWithParentheses:
  Enabled: true
Layout/EmptyLineBetweenDefs:
  Enabled: true
Layout/EmptyLines:
  Enabled: true
Layout/ExtraSpacing:
  Enabled: true
Layout/GuardClause:
  Enabled: true
Layout/IdenticalConditionalBranches:
  Enabled: true
Layout/InverseMethods:
  Enabled: true
Layout/LeadingCommentSpace:
  Enabled: true
Layout/MethodName:
  Enabled: true
Layout/NegatedIf:
  Enabled: true
Layout/NegatedWhile:
  Enabled: true
Layout/NilComparison:
  Enabled: true
Layout/Not:
  Enabled: true
Layout/NumericLiterals:
  Enabled: true
Layout/NumericPredicate:
  Enabled: true
Layout/OneLineConditional:
  Enabled: true
Layout/PredicateName:
  Enabled: true
Layout/RedundantParentheses:
  Enabled: true
Layout/RedundantSelf:
  Enabled: true
Layout/SafeNavigation:
  Enabled: true
Layout/SelfAssignment:
  Enabled: true
Layout/SpaceAfterColon:
  Enabled: true
Layout/SpaceAfterComma:
  Enabled: true
Layout/SpaceAfterMethodName:
  Enabled: true
Layout/SpaceAfterNot:
  Enabled: true
Layout/SpaceAfterSemicolon:
  Enabled: true
Layout/SpaceAroundBlockParameters:
  Enabled: true
Layout/SpaceAroundEqualsInParameterDefault:
  Enabled: true
Layout/SpaceAroundKeyword:
  Enabled: true
Layout/SpaceAroundOperators:
  Enabled: true
Layout/SpaceBeforeBlockBraces:
  Enabled: true
Layout/SpaceBeforeComma:
  Enabled: true
Layout/SpaceBeforeComment:
  Enabled: true
Layout/SpaceBeforeFirstArg:
  Enabled: true
Layout/SpaceBeforeSemicolon:
  Enabled: true
Layout/SpaceInLambdaLiteral:
  Enabled: true
Layout/SpaceInsideArrayPercentLiteral:
  Enabled: true
Layout/SpaceInsideBlockBraces:
  Enabled: true
Layout/SpaceInsideBrackets:
  Enabled: true
Layout/SpaceInsideHashLiteralBraces:
  Enabled: true
Layout/SpaceInsideParens:
  Enabled: true
Layout/SpaceInsidePercentLiteralDelimiters:
  Enabled: true
Layout/SpaceInsideRangeLiteral:
  Enabled: true
Layout/SpaceInsideStringInterpolation:
  Enabled: true
Layout/SymbolLiteral:
  Enabled: true
Layout/TrailingBlankLines:
  Enabled: true
Layout/TrivialAccessors:
  Enabled: true
Layout/VariableName:
  Enabled: true
Layout/FileName:
  Enabled: true

# Rubocop doesn't make disabling all cops in a given group easy, so we list...
Layout/AccessModifierIndentation:
  Enabled: false
Layout/Alias:
  Enabled: false
Layout/AlignArray:
  Enabled: false
Layout/AlignHash:
  Enabled: false
Layout/AlignParameters:
  Enabled: false
Layout/AndOr:
  Enabled: false
Layout/ArrayJoin:
  Enabled: false
Layout/AsciiComments:
  Enabled: false
Layout/AsciiIdentifiers:
  Enabled: false
Layout/Attr:
  Enabled: false
Layout/AutoResourceCleanup:
  Enabled: false
Layout/BarePercentLiterals:
  Enabled: false
Layout/BeginBlock:
  Enabled: false
Layout/BlockComments:
  Enabled: false
Layout/BlockDelimiters:
  Enabled: false
Layout/BracesAroundHashParameters:
  Enabled: false
Layout/CaseEquality:
  Enabled: false
Layout/CaseIndentation:
  Enabled: false
Layout/CharacterLiteral:
  Enabled: false
Layout/ClassAndModuleChildren:
  Enabled: false
Layout/ClassCheck:
  Enabled: false
Layout/ClassMethods:
  Enabled: false
Layout/ClassVars:
  Enabled: false
Layout/ClosingParenthesisIndentation:
  Enabled: false
Layout/CollectionMethods:
  Enabled: false
Layout/ColonMethodCall:
  Enabled: false
Layout/CommandLiteral:
  Enabled: false
Layout/CommentAnnotation:
  Enabled: false
Layout/CommentIndentation:
  Enabled: false
Layout/ConditionalAssignment:
  Enabled: false
Layout/Copyright:
  Enabled: false
Layout/Documentation:
  Enabled: false
Layout/DocumentationMethod:
  Enabled: false
Layout/DotPosition:
  Enabled: false
Layout/DoubleNegation:
  Enabled: false
Layout/EachForSimpleLoop:
  Enabled: false
Layout/EachWithObject:
  Enabled: false
Layout/ElseAlignment:
  Enabled: false
Layout/EmptyCaseCondition:
  Enabled: false
Layout/EmptyElse:
  Enabled: false
Layout/EmptyLineAfterMagicComment:
  Enabled: false
Layout/EmptyLinesAroundAccessModifier:
  Enabled: false
Layout/EmptyLinesAroundBeginBody:
  Enabled: false
Layout/EmptyLinesAroundBlockBody:
  Enabled: false
Layout/EmptyLinesAroundClassBody:
  Enabled: false
Layout/EmptyLinesAroundExceptionHandlingKeywords:
  Enabled: false
Layout/EmptyLinesAroundMethodBody:
  Enabled: false
Layout/EmptyLinesAroundModuleBody:
  Enabled: false
Layout/EmptyLiteral:
  Enabled: false
Layout/EmptyMethod:
  Enabled: false
Layout/Encoding:
  Enabled: false
Layout/EndBlock:
  Enabled: false
Layout/EndOfLine:
  Enabled: false
Layout/EvenOdd:
  Enabled: false
Layout/FirstArrayElementLineBreak:
  Enabled: false
Layout/FirstHashElementLineBreak:
  Enabled: false
Layout/FirstMethodArgumentLineBreak:
  Enabled: false
Layout/FirstMethodParameterLineBreak:
  Enabled: false
Layout/FirstParameterIndentation:
  Enabled: false
Layout/FlipFlop:
  Enabled: false
Layout/For:
  Enabled: false
Layout/FormatString:
  Enabled: false
Layout/FrozenStringLiteralComment:
  Enabled: false
Layout/GlobalVars:
  Enabled: false
Layout/HashSyntax:
  Enabled: false
Layout/IfInsideElse:
  Enabled: false
Layout/IfUnlessModifier:
  Enabled: false
Layout/IfUnlessModifierOfIfUnless:
  Enabled: false
Layout/IfWithSemicolon:
  Enabled: false
Layout/ImplicitRuntimeError:
  Enabled: false
Layout/IndentArray:
  Enabled: false
Layout/IndentAssignment:
  Enabled: false
Layout/IndentHash:
  Enabled: false
Layout/IndentHeredoc:
  Enabled: false
Layout/InfiniteLoop:
  Enabled: false
Layout/InitialIndentation:
  Enabled: false
Layout/InlineComment:
  Enabled: false
Layout/Lambda:
  Enabled: false
Layout/LambdaCall:
  Enabled: false
Layout/LineEndConcatenation:
  Enabled: false
Layout/MethodCallWithArgsParentheses:
  Enabled: false
Layout/MethodCallWithoutArgsParentheses:
  Enabled: false
Layout/MethodCalledOnDoEndBlock:
  Enabled: false
Layout/MethodDefParentheses:
  Enabled: false
Layout/MethodMissing:
  Enabled: false
Layout/MissingElse:
  Enabled: false
Layout/MixinGrouping:
  Enabled: false
Layout/ModuleFunction:
  Enabled: false
Layout/MultilineArrayBraceLayout:
  Enabled: false
Layout/MultilineAssignmentLayout:
  Enabled: false
Layout/MultilineBlockChain:
  Enabled: false
Layout/MultilineBlockLayout:
  Enabled: false
Layout/MultilineHashBraceLayout:
  Enabled: false
Layout/MultilineIfModifier:
  Enabled: false
Layout/MultilineIfThen:
  Enabled: false
Layout/MultilineMemoization:
  Enabled: false
Layout/MultilineMethodCallBraceLayout:
  Enabled: false
Layout/MultilineMethodCallIndentation:
  Enabled: false
Layout/MultilineMethodDefinitionBraceLayout:
  Enabled: false
Layout/MultilineOperationIndentation:
  Enabled: false
Layout/MultilineTernaryOperator:
  Enabled: false
Layout/MutableConstant:
  Enabled: false
Layout/NestedModifier:
  Enabled: false
Layout/NestedParenthesizedCalls:
  Enabled: false
Layout/NestedTernaryOperator:
  Enabled: false
Layout/Next:
  Enabled: false
Layout/NonNilCheck:
  Enabled: false
Layout/NumericLiteralPrefix:
  Enabled: false
Layout/OpMethod:
  Enabled: false
Layout/OptionHash:
  Enabled: false
Layout/OptionalArguments:
  Enabled: false
Layout/ParallelAssignment:
  Enabled: false
Layout/ParenthesesAroundCondition:
  Enabled: false
Layout/PercentLiteralDelimiters:
  Enabled: false
Layout/PercentQLiterals:
  Enabled: false
Layout/PerlBackrefs:
  Enabled: false
Layout/PreferredHashMethods:
  Enabled: false
Layout/Proc:
  Enabled: false
Layout/RaiseArgs:
  Enabled: false
Layout/RedundantBegin:
  Enabled: false
Layout/RedundantException:
  Enabled: false
Layout/RedundantFreeze:
  Enabled: false
Layout/RedundantReturn:
  Enabled: false
Layout/RegexpLiteral:
  Enabled: false
Layout/RescueEnsureAlignment:
  Enabled: false
Layout/RescueModifier:
  Enabled: false
Layout/Semicolon:
  Enabled: false
Layout/Send:
  Enabled: false
Layout/SignalException:
  Enabled: false
Layout/SingleLineBlockParams:
  Enabled: false
Layout/SingleLineMethods:
  Enabled: false
Layout/SpecialGlobalVars:
  Enabled: false
Layout/StabbyLambdaParentheses:
  Enabled: false
Layout/StringLiterals:
  Enabled: false
Layout/StringLiteralsInInterpolation:
  Enabled: false
Layout/StringMethods:
  Enabled: false
Layout/StructInheritance:
  Enabled: false
Layout/SymbolArray:
  Enabled: false
Layout/SymbolProc:
  Enabled: false
Layout/Tab:
  Enabled: false
Layout/TernaryParentheses:
  Enabled: false
Layout/TrailingCommaInArguments:
  Enabled: false
Layout/TrailingCommaInLiteral:
  Enabled: false
Layout/TrailingUnderscoreVariable:
  Enabled: false
Layout/TrailingWhitespace:
  Enabled: false
Layout/UnlessElse:
  Enabled: false
Layout/UnneededCapitalW:
  Enabled: false
Layout/UnneededInterpolation:
  Enabled: false
Layout/UnneededPercentQ:
  Enabled: false
Layout/VariableInterpolation:
  Enabled: false
Layout/VariableNumber:
  Enabled: false
Layout/WhenThen:
  Enabled: false
Layout/WhileUntilDo:
  Enabled: false
Layout/WhileUntilModifier:
  Enabled: false
Layout/WordArray:
  Enabled: false
Layout/ZeroLengthPredicate:
  Enabled: false
