#!/bin/bash

clear
echo "You are about to pull, push, then pull again"
read -r -p "Are you sure? [y/N] " response
if [[ "$response" =~ ^([yY][eE][sS]|[yY])$ ]]
then
  CMD="git pull"
  echo -e "$HOSTNAME\$ $CMD\n"
  $CMD

  CMD="git push"
  echo -e "\n$HOSTNAME\$ $CMD\n"
  $CMD

  CMD="git pull"
  echo -e "\n$HOSTNAME\$ $CMD\n"
  $CMD

  CMD="git status"
  echo -e "$HOSTNAME\$ $CMD\n"
  $CMD

  CMD="git log -8 --oneline --color=always"
  echo -e "\n$HOSTNAME\$ $CMD\n"
  $CMD
else
    exit
fi


