# Generated by cucumber-sinatra. (2015-02-20 13:38:18 +0000)

ENV['RACK_ENV'] = 'test'

require File.join(File.dirname(__FILE__), '..', '..', '..', './server.rb')

require 'capybara'
require 'capybara/cucumber'
require 'rspec'

Capybara.app = Rock_paper_scissors.new

class Rock_paper_scissorsWorld
  include Capybara::DSL
  include RSpec::Expectations
  include RSpec::Matchers
end

World do
  Rock_paper_scissorsWorld.new
end
