# A sample Gemfile
ruby '2.2.0'
source "https://rubygems.org"

gem 'sinatra'

group :development, :test do
  gem 'capybara'
  gem 'cucumber'
  gem 'cucumber-sinatra'
  gem 'launchy'
  gem 'rspec'
  gem 'shotgun'
end
