# # Generated by cucumber-sinatra. (2015-02-17 16:31:19 +0000)

# ENV['RACK_ENV'] = 'test'

# require File.join(File.dirname(__FILE__), '..', '..', '..' 'app/server.rb')

# require 'capybara'
# require 'capybara/cucumber'
# require 'rspec'

# Capybara.app = BattleShips

# class BattleShipsWorld
#   include Capybara::DSL
#   include RSpec::Expectations
#   include RSpec::Matchers
# end

# World do
#   BattleShipsWorld.new
# end

ENV['RACK_ENV'] = 'test'

require './app/server'
require 'capybara'
require 'capybara/cucumber'
require 'cucumber/rspec/doubles'

Capybara.app = Sinatra::Application

