source 'https://rubygems.org'

ruby '3.0.2'

gem 'sinatra'
gem 'sinatra-contrib'

group :test do
  gem 'capybara'
  gem 'rspec'
  gem 'simplecov'
  gem 'simplecov-console'
  gem 'webrick'
  gem 'launchy'
end

group :development, :test do
  gem 'rubocop', '1.20'
end
